import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:tiktok_challenge/constants/gaps.dart';
import 'package:tiktok_challenge/constants/sizes.dart';

class InterestsDetailScreen extends StatelessWidget {
  InterestsDetailScreen({super.key});
  final Map<String, List<String>> interestDetails = {
    "Fashion & beauty": [
      "Makeup trends",
      "Skincare routines",
      "Hairstyles",
      "Street fashion",
      "Luxury brands",
      "Fashion shows",
      "Modeling",
      "Cosmetics industry",
      "Nail art",
      "Perfumes",
      "Wardrobe styling",
      "Sustainable fashion",
      "Designer collections",
      "Fashion magazines",
      "Beauty influencers",
      "Men’s fashion",
      "Accessories",
      "Runway highlights",
      "DIY beauty",
      "Seasonal looks",
    ],
    "Outdoors": [
      "Camping",
      "Hiking",
      "Fishing",
      "Backpacking",
      "National parks",
      "Wildlife watching",
      "Kayaking",
      "Rock climbing",
      "Cycling",
      "Trail running",
      "Nature photography",
      "Outdoor gear",
      "Survival skills",
      "Eco-tourism",
      "Mountain climbing",
      "Scuba diving",
      "Snowboarding",
      "Skiing",
      "Bird watching",
      "Adventure travel",
    ],
    "Arts & culture": [
      "Painting",
      "Sculpture",
      "Museums",
      "Art exhibitions",
      "Modern art",
      "Classical art",
      "Street art",
      "Cultural festivals",
      "Architecture",
      "Opera",
      "Theater",
      "Dance",
      "Art history",
      "Photography",
      "Design",
      "Crafts",
      "Calligraphy",
      "Ceramics",
      "Literary arts",
      "Cultural heritage",
    ],
    "Animation & comics": [
      "Anime",
      "Manga",
      "Cartoons",
      "Comic books",
      "Marvel comics",
      "DC comics",
      "Webtoons",
      "Graphic novels",
      "Superheroes",
      "Villains",
      "Fantasy worlds",
      "Sci-fi comics",
      "Comic conventions",
      "Fan art",
      "Cosplay",
      "Animation studios",
      "Voice acting",
      "Storyboarding",
      "Indie comics",
      "Comic news",
    ],
    "Business & finance": [
      "Stock market",
      "Investing",
      "Startups",
      "Entrepreneurship",
      "Banking",
      "Cryptocurrency",
      "Real estate",
      "Economics",
      "Business news",
      "Marketing",
      "Management",
      "Accounting",
      "E-commerce",
      "Global trade",
      "Business strategy",
      "Financial planning",
      "Insurance",
      "Corporate culture",
      "Leadership",
      "Business ethics",
    ],
    "Food": [
      "Recipes",
      "Cooking tips",
      "Street food",
      "Fine dining",
      "Baking",
      "Desserts",
      "Healthy eating",
      "Vegetarian",
      "Vegan",
      "BBQ",
      "Seafood",
      "Snacks",
      "Food festivals",
      "Wine",
      "Coffee",
      "Tea",
      "Food photography",
      "World cuisines",
      "Food reviews",
      "Nutrition",
    ],
    "Travel": [
      "Adventure travel",
      "Luxury travel",
      "Budget travel",
      "Solo travel",
      "Group tours",
      "Road trips",
      "Backpacking",
      "Cultural travel",
      "Beach destinations",
      "Mountains",
      "City breaks",
      "Travel tips",
      "Travel photography",
      "Airlines",
      "Hotels",
      "Hostels",
      "Travel blogs",
      "Travel gear",
      "Eco travel",
      "Cruises",
    ],
    "Entertainment": [
      "Anime",
      "Movies & TV",
      "Harry Potter",
      "Marvel Universe",
      "Movie news",
      "Naruto",
      "Movies",
      "TV shows",
      "Celebrities",
      "Awards shows",
      "Streaming platforms",
      "Sitcoms",
      "Drama series",
      "Reality TV",
      "Music festivals",
      "Concerts",
      "Comedy",
      "Talk shows",
      "Entertainment news",
      "Pop culture",
    ],
    "Music": [
      "Rap",
      "R&B & soul",
      "Grammy Awards",
      "Pop",
      "K-pop",
      "Music industry",
      "EDM",
      "Music news",
      "Hip hop",
      "Reggae",
      "Jazz",
      "Classical",
      "Rock",
      "Indie",
      "Country",
      "Metal",
      "Soundtracks",
      "Live concerts",
      "Music festivals",
      "Songwriting",
    ],
    "Gaming": [
      "PC games",
      "Console games",
      "Mobile games",
      "Esports",
      "Game reviews",
      "RPG",
      "MMORPG",
      "FPS",
      "Strategy games",
      "Indie games",
      "Retro games",
      "Game development",
      "Streaming",
      "Game news",
      "Simulation games",
      "Adventure games",
      "Puzzle games",
      "VR gaming",
      "AR gaming",
      "Board games",
    ],
    "Sports": [
      "Soccer",
      "Basketball",
      "Baseball",
      "Tennis",
      "Golf",
      "Running",
      "Cycling",
      "Swimming",
      "Boxing",
      "Martial arts",
      "Olympics",
      "Winter sports",
      "Extreme sports",
      "Volleyball",
      "Cricket",
      "Rugby",
      "Table tennis",
      "Badminton",
      "Sports news",
      "Sports gear",
    ],
    "Technology": [
      "AI",
      "Robotics",
      "Smartphones",
      "Computers",
      "Software",
      "Hardware",
      "Cloud computing",
      "Cybersecurity",
      "Blockchain",
      "IoT",
      "AR/VR",
      "Wearables",
      "Tech startups",
      "Programming",
      "Web development",
      "Gadgets",
      "Tech news",
      "Data science",
      "Machine learning",
      "Space tech",
    ],
    "Health & fitness": [
      "Workout routines",
      "Yoga",
      "Pilates",
      "Meditation",
      "Nutrition",
      "Healthy recipes",
      "Weight loss",
      "Cardio",
      "Strength training",
      "CrossFit",
      "Running",
      "Cycling",
      "Mental health",
      "Wellness tips",
      "Fitness gear",
      "Sports medicine",
      "Personal training",
      "Healthy lifestyle",
      "Sleep health",
      "Mindfulness",
    ],
    "Education": [
      "Schools",
      "Universities",
      "Online learning",
      "E-learning platforms",
      "Study tips",
      "Exams",
      "Scholarships",
      "Tutoring",
      "STEM",
      "Languages",
      "History",
      "Math",
      "Science",
      "Literature",
      "Educational apps",
      "Teaching methods",
      "Classroom tech",
      "Education policy",
      "Student life",
      "Research",
    ],
    "Science": [
      "Physics",
      "Chemistry",
      "Biology",
      "Astronomy",
      "Geology",
      "Environmental science",
      "Space exploration",
      "Genetics",
      "Medicine",
      "Scientific research",
      "Science news",
      "Nanotechnology",
      "Marine biology",
      "Botany",
      "Zoology",
      "Climate science",
      "Archaeology",
      "Anthropology",
      "Neuroscience",
      "Mathematics",
    ],
    "Photography": [
      "Portraits",
      "Landscapes",
      "Street photography",
      "Wildlife photography",
      "Macro photography",
      "Fashion photography",
      "Sports photography",
      "Event photography",
      "Wedding photography",
      "Travel photography",
      "Photo editing",
      "Cameras",
      "Lenses",
      "Lighting",
      "Photography tips",
      "Photojournalism",
      "Black & white",
      "Film photography",
      "Digital photography",
      "Drone photography",
    ],
    "Movies & TV": [
      "Hollywood",
      "Bollywood",
      "Movie reviews",
      "TV series",
      "Streaming",
      "Netflix",
      "Disney",
      "Marvel movies",
      "DC movies",
      "Movie trailers",
      "Actors",
      "Directors",
      "Screenwriting",
      "Film festivals",
      "Documentaries",
      "Sitcoms",
      "Drama",
      "Reality shows",
      "Movie awards",
      "TV news",
    ],
    "Literature": [
      "Novels",
      "Poetry",
      "Short stories",
      "Drama",
      "Classics",
      "Modern literature",
      "Fantasy",
      "Sci-fi",
      "Mystery",
      "Romance",
      "Non-fiction",
      "Biographies",
      "Literary criticism",
      "Book reviews",
      "Authors",
      "Publishing",
      "Libraries",
      "Literary awards",
      "Children’s books",
      "Writing tips",
    ],
    "DIY & crafts": [
      "Knitting",
      "Crochet",
      "Embroidery",
      "Sewing",
      "Woodworking",
      "Paper crafts",
      "Origami",
      "Jewelry making",
      "Pottery",
      "Scrapbooking",
      "Home decor DIY",
      "Upcycling",
      "Glass painting",
      "Resin art",
      "Macrame",
      "Candle making",
      "Soap making",
      "Handmade gifts",
      "DIY furniture",
      "Craft fairs",
    ],
    "Pets & animals": [
      "Dogs",
      "Cats",
      "Birds",
      "Fish",
      "Reptiles",
      "Small mammals",
      "Pet care",
      "Pet training",
      "Pet adoption",
      "Veterinary tips",
      "Wild animals",
      "Animal rescue",
      "Animal rights",
      "Exotic pets",
      "Pet grooming",
      "Pet nutrition",
      "Pet toys",
      "Pet accessories",
      "Animal photography",
      "Animal behavior",
    ],
  };

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        surfaceTintColor: Colors.transparent,
        elevation: 0,
        title: Center(
          child: FaIcon(
            FontAwesomeIcons.twitter,
            color: Theme.of(context).primaryColor,
            size: Sizes.size28,
          ),
        ),
      ),
      body: Column(
        children: [
          Padding(
            padding: const EdgeInsets.only(
              top: Sizes.size5,
              left: Sizes.size20,
              right: Sizes.size20,
              bottom: Sizes.size5,
            ),
            child: Column(
              children: [
                Text(
                  "What do you want to see on Twitter?",
                  style: TextStyle(
                    fontSize: Sizes.size36,
                    fontWeight: FontWeight.w900,
                  ),
                ),
                Gaps.v16,
                Text(
                  "Interests are used to personalize your experience and will be visible on your profile.",
                  style: TextStyle(fontSize: Sizes.size16),
                ),
              ],
            ),
          ),
          Gaps.v28,
          Divider(
            color: Colors.grey.shade400,
            height: Sizes.size2,
            thickness: 0,
          ),
          Gaps.v24,
        ],
      ),
    );
  }
}
